name: Deploy Angular App to Droplet

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH and deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.PRIVATE_KEY }}
        passphrase: ${{ secrets.PRIVATE_KEY_PASSHRASE }}
        script: |
          cd ~/S3ImageFrontEndUpload
          git pull origin master
          npm install
          ng build --configuration=production
          cp -R dist/s3-image-upload/* /var/www/angular-app/
